import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Weekly Market Signal Report | Signal Relay Hub',
  description: 'Review the top 5 most profitable market signals generated by our AI this week. See how SEC filings and economic data translated into live trade setups.',
  openGraph: {
    title: 'Weekly Market Signal Report | Signal Relay Hub',
    description: 'Review the top AI-generated market signals of the week.',
    url: 'https://www.signalrelayhub.io/weekly-report',
    siteName: 'Signal Relay Hub',
  },
};

const WEEKLY_SIGNALS = [
  { 
    id: 1, 
    date: 'Mon, 08:30 UTC', 
    catalyst: 'Coinbase SEC 8-K Filing — Regulatory expansion approved in EU.', 
    pair: 'BTCUSD', 
    direction: 'LONG', 
    aiPrediction: 'Bullish breakout expected above key resistance. Entry: 64,200',
    outcome: '+3.4% profit hit target in 4 hours',
    status: 'win'
  },
  { 
    id: 2, 
    date: 'Wed, 13:30 UTC', 
    catalyst: 'US CPI Data — Inflation comes in hotter than expected (0.4% vs 0.3%).', 
    pair: 'XAUUSD', 
    direction: 'SHORT', 
    aiPrediction: 'Hawkish repricing of Fed rates. Sell gold on spike. Entry: 2340',
    outcome: '+120 pips hit target in 6 hours',
    status: 'win'
  },
  { 
    id: 3, 
    date: 'Thu, 15:00 UTC', 
    catalyst: 'OpenAI Product Announcement — Sora video model updates.', 
    pair: 'US30', 
    direction: 'LONG', 
    aiPrediction: 'Tech sector boost expected. Broad market bullish. Entry: 38,900',
    outcome: 'Stopped out at break-even due to broader macro drag',
    status: 'neutral'
  },
];

export default function WeeklyReportPage() {
  return (
    <div className="relative min-h-screen overflow-hidden bg-neutral-950 text-white">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(16,185,129,0.15),_transparent_50%)]" />
      
      <div className="relative mx-auto flex min-h-screen max-w-4xl flex-col px-6 py-10">
        <header className="flex items-center justify-between mb-16">
          <Link href="/" className="text-lg font-semibold hover:opacity-80 transition-opacity">Signal Relay Hub</Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link className="text-white/70 hover:text-white transition-colors" href="/login">Sign in</Link>
            <Link className="rounded-full bg-white px-4 py-2 font-semibold text-neutral-900 hover:bg-neutral-200 transition-colors" href="/pricing">Get started</Link>
          </nav>
        </header>

        <main className="flex-1 space-y-12">
          <div>
            <div className="inline-flex items-center rounded-full bg-white/10 px-3 py-1 text-xs uppercase tracking-wide text-neutral-200 mb-4">
              Weekly Recap — Vol 42
            </div>
            <h1 className="text-4xl font-semibold leading-tight sm:text-5xl">Top AI Signals of the Week</h1>
            <p className="mt-4 text-lg text-white/60">
              A transparent review of how our AI pipeline mapped real-world data (SEC filings, macroeconomic releases, and fintech news) directly into actionable market setups this week.
            </p>
          </div>

          <div className="space-y-6">
            {WEEKLY_SIGNALS.map((signal) => (
              <div key={signal.id} className="rounded-3xl border border-white/10 bg-white/5 p-6 sm:p-8">
                <div className="flex flex-wrap items-center justify-between gap-4 mb-4">
                  <span className="text-xs font-mono text-white/40">{signal.date}</span>
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-white">{signal.pair}</span>
                    <span className={`rounded px-2 py-0.5 text-xs font-bold ${signal.direction === 'LONG' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-rose-500/20 text-rose-400'}`}>
                      {signal.direction}
                    </span>
                  </div>
                </div>

                <h3 className="text-lg font-medium text-white mb-4">{signal.catalyst}</h3>
                
                <div className="grid gap-4 sm:grid-cols-2 mt-6 border-t border-white/10 pt-6">
                  <div>
                    <div className="text-xs uppercase tracking-wide text-white/40 mb-1">AI Prediction at exact time of release</div>
                    <div className="text-sm text-white/80">{signal.aiPrediction}</div>
                  </div>
                  <div className="rounded-xl border border-white/5 bg-black/40 p-3">
                    <div className="text-xs uppercase tracking-wide text-white/40 mb-1">Actual Outcome</div>
                    <div className={`text-sm font-semibold ${signal.status === 'win' ? 'text-emerald-400' : 'text-white/60'}`}>
                      {signal.status === 'win' ? '✓ ' : '— '}{signal.outcome}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="rounded-3xl border border-emerald-500/20 bg-gradient-to-b from-emerald-500/10 to-neutral-900 p-8 text-center sm:p-12">
            <h2 className="text-2xl font-semibold text-white">Stop reading history. Start trading it live.</h2>
            <p className="mt-2 text-white/60 max-w-xl mx-auto">
              By the time this weekly report comes out, the moves have already happened. Get these exact AI-mapped trade setups delivered directly to your Telegram the second the data drops.
            </p>
            <div className="mt-6 flex justify-center gap-4">
              <Link href="/plans" className="rounded-full bg-emerald-500 px-6 py-3 text-sm font-bold text-neutral-900 hover:bg-emerald-400 transition-colors">
                Get Live Trade Setups
              </Link>
            </div>
          </div>
        </main>

        <footer className="mt-20 border-t border-white/5 pt-8 text-xs text-white/40 flex justify-between">
          <span>© {new Date().getFullYear()} Signal Relay Hub</span>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
          </div>
        </footer>
      </div>
    </div>
  );
}
