export default function DisclaimerPage() {
  return (
    <div className="space-y-6 text-white">
      <section className="rounded-3xl bg-neutral-950 p-8 shadow-xl">
        <p className="text-xs uppercase tracking-[0.3em] text-amber-400/70">Legal</p>
        <h1 className="mt-3 text-3xl font-semibold">Risk Disclaimer</h1>
        <p className="mt-3 text-sm text-white/60">Last updated: April 2026</p>
      </section>

      <section className="rounded-3xl border border-white/10 bg-white/5 p-8 space-y-6 text-sm text-white/70 leading-relaxed">
        <div>
          <h2 className="text-white font-semibold mb-2">Not Financial Advice</h2>
          <p>Signal Relay Hub provides market intelligence, news aggregation and AI-generated analysis strictly for educational and informational purposes. Nothing published on this platform — including signals, trade predictions, market analysis, AI briefings, pre-event alerts, post-event debriefs, weekly outlooks or community discussions — constitutes financial advice, investment advice, trading advice, or any other form of advice regulated by the Financial Conduct Authority (FCA) or any other regulatory body.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold mb-2">AI-Generated Content</h2>
          <p>Trade predictions, market analysis and briefings on this platform are generated by artificial intelligence systems (Anthropic Claude) and are automated. They may be inaccurate, incomplete, delayed or based on incorrect data. AI-generated content should never be used as the sole basis for any trading or investment decision.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold mb-2">Trading Risk Warning</h2>
          <p>Trading financial instruments including but not limited to foreign exchange (forex), cryptocurrencies, commodities, indices and equities involves substantial risk of loss. You may lose more than your initial deposit. Leveraged products can result in losses that exceed your initial investment. Trading is not suitable for all investors. The value of investments can go down as well as up.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold mb-2">Past Performance</h2>
          <p>Past signal performance, prediction accuracy rates and historical analysis do not guarantee future results. Any statistics displayed on this platform regarding signal accuracy or prediction performance are illustrative only and should not be relied upon.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold mb-2">No Liability</h2>
          <p>Signal Relay Hub, its operators, employees, contributors and affiliates accept no responsibility or liability for any losses, damages or costs incurred as a result of using information published on this platform. By accessing and using Signal Relay Hub you agree that you do so entirely at your own risk.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold mb-2">Your Responsibility</h2>
          <p>You are solely responsible for your own trading and investment decisions. Always conduct your own independent research. Always consult a qualified and regulated financial adviser before making any trading or investment decisions. Never trade with money you cannot afford to lose.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold mb-2">Regulatory Status</h2>
          <p>Signal Relay Hub is not authorised or regulated by the Financial Conduct Authority (FCA) or any other financial regulatory authority. We do not provide regulated financial services. We are a market intelligence and data aggregation platform.</p>
        </div>

        <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4">
          <p className="text-amber-400/80 font-medium">By continuing to use Signal Relay Hub you confirm that you have read, understood and agreed to this disclaimer and that you accept all risks associated with trading financial markets.</p>
        </div>
      </section>
    </div>
  );
}
